### ISSUE TITLE
git-r3 variable EGIT_REPO_URI not supported

### ISSUE THREAD

**Issue by archenroot** [gentoo/lua#2]
Either GITHUB_A or BITBUCKET_A (author nick) should be set for magic SRC/REPO URI filling to work
 * You should either set one of them, or fill the proper URI variable manually!
 * ERROR: dev-lua/torch-paths-9999::archenroot failed (unpack phase):
 *   See above eerror messages.

In general you introduce here variable which might be rather included in git-r3 standard Gentoo variable, don't you think?

**Comment by msva** [comment]
`lua.eclass`'s default unpack phase function assumes that you would not include `git-r3` eclass by hand, but instead specify "magic" variable `VCS="git"` (to fall to `lua.eclass`'s default (`git-r3` ATM) eclass, or `git-r3` to manually bind ebuild to `git-r3` eclass) **before** the `inherit` line.

**Comment by msva** [comment]
... and since package is anyway hosted on github, you can also set few more magic variables:
```
GITHUB_A="torch"
GITHUB_PN="paths"
```

That would ease migration to forks (in case it would be needed) for you, and for end user (through `${EROOT}etc/portage/env/dev-lua/pkgname`)

**Comment by archenroot** [comment]
I finally found it by exploring the eclass and other ebuilds in your repository. Thanks for confirmation buddy!
