### ISSUE TITLE
resty-core missing libs

### ISSUE THREAD

**Issue by transtone** [gentoo/lua#6]
lua-resty-core has many funciton in https://github.com/openresty/lua-resty-core/tree/master/lib/ngx, 
but the ebuild only take resty. 

```
each_lua_install() {
    dolua_jit lib/resty
    dolua_jit lib/ngx
}
```

please add `lib/ngx` like above.

**Comment by msva** [comment]
Unfortunatelly, I stopped maintenance of packages in this repo, and moved all the stuff to my personal repo (to avoid doble maintenance work here and there).
And also because it was problems with commits signatures.

You can use `mva` overlay for now.
